name: SLSA Provenance Generation Workflow

on:
  push:
    branches:
      - main

jobs:
  slsa-generation-job:
    runs-on: self-hosted

    env:
      HARNESS_ACCOUNT_URL: 'https://qa.harness.io'
      HARNESS_ACCOUNT_ID: 'ppbLW9YpRharzPs_JtWT7g'
      HARNESS_ORG_ID: 'default'
      HARNESS_PROJECT_ID: 'Product_Exploratory'
      HARNESS_API_KEY: ${{ secrets.SCS_API_KEY }}
      # VAULT_ADDR: ${{ secrets.VAULT_URL }}

    steps:
      # Step 1: Checkout the main repository
      - name: Checkout Main Repository
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and Tag Docker Image
      - name: Build and Tag Docker Image
        run: |
          docker build -t lavakush07/easy-buggy-app:SLSA -f ./stable/alpine/Dockerfile .
          echo "Docker image built and tagged as lavakush07/easy-buggy-app:SLSA."

      # Step 4: Push Docker Image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push lavakush07/easy-buggy-app:SLSA
          echo "Docker image pushed to Docker Hub."

      # Step 5: Log in to Vault
      # - name: Log in to Vault
      #   uses: hashicorp/vault-action@v2
      #   with:
      #     url: ${{ secrets.VAULT_URL }}
      #     method: token
      #     token: ${{ secrets.VAULT_TOKEN }}

      # Step 6: Run SLSA Provenance Generation
      - name: Run SLSA Provenance Action
        uses: ./slsa-generation
        with:
          TARGET: 'harness/github-service:latest'
          ATTEST: true
          KMS_KEY: 'cosign'

